name: 🐛 Bug | Bug Report
description: 回報錯誤或異常問題 | Report an error or unexpected behavior
title: "[Bug]: "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **提交問題前，請確保您已閱讀以下文件：[Getting Started (English)](https://github.com/terryuuang/MoneyPrinterTurbo/blob/main/README-en.md#system-requirements-) 或 [快速開始 (中文)](https://github.com/terryuuang/MoneyPrinterTurbo/blob/main/README.md#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B-)。**

        **Before submitting an issue, please make sure you've read the following documentation: [Getting Started (English)](https://github.com/terryuuang/MoneyPrinterTurbo/blob/main/README-en.md#system-requirements-) or [快速開始 (Chinese)](https://github.com/terryuuang/MoneyPrinterTurbo/blob/main/README.md#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B-).**

  - type: textarea
    attributes:
      label: 問題描述 | Current Behavior
      description: |
        描述您遇到的問題
        Describe the issue you're experiencing
      placeholder: |
        當我執行...操作時，程式出現了...問題
        When I perform..., the program shows...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 重現步驟 | Steps to Reproduce
      description: |
        詳細描述如何重現此問題
        Describe in detail how to reproduce this issue
      placeholder: |
        1. 開啟...
        2. 點擊...
        3. 出現錯誤...

        1. Open...
        2. Click on...
        3. Error occurs...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 錯誤日誌 | Error Logs
      description: |
        請提供相關錯誤資訊或日誌（注意不要包含敏感資訊）
        Please provide any error messages or logs (be careful not to include sensitive information)
      placeholder: |
        錯誤訊息、日誌或螢幕截圖...
        Error messages, logs, or screenshots...
    validations:
      required: true
  - type: input
    attributes:
      label: Python 版本 | Python Version
      description: |
        您使用的 Python 版本
        The Python version you're using
      placeholder: v3.13.0, v3.10.0, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: 作業系統 | Operating System
      description: |
        您的作業系統資訊
        Your operating system information
      placeholder: macOS 14.1, Windows 11, Ubuntu 22.04, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: MoneyPrinterTurbo 版本 | Version
      description: |
        您使用的 MoneyPrinterTurbo 版本
        The version of MoneyPrinterTurbo you're using
      placeholder: v1.2.2, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 補充資訊 | Additional Information
      description: |
        其他對解決問題有幫助的資訊（如螢幕截圖、影片等）
        Any other information that might help solve the issue (screenshots, videos, etc.)
    validations:
      required: false